insert into Threehurdle_Score(age,num,score) values('18','3.50','3');
insert into Threehurdle_Score(age,num,score) values('18','3.40','2');
insert into Threehurdle_Score(age,num,score) values('18','3.30','1');
insert into Threehurdle_Score(age,num,score) values('19','3.50','3');
insert into Threehurdle_Score(age,num,score) values('19','3.40','2');
insert into Threehurdle_Score(age,num,score) values('19','3.30','1');

insert into Threehurdle_Score(age,num,score) values('20','3.40','3');
insert into Threehurdle_Score(age,num,score) values('20','3.30','2');
insert into Threehurdle_Score(age,num,score) values('20','3.20','1');
insert into Threehurdle_Score(age,num,score) values('21','3.40','3');
insert into Threehurdle_Score(age,num,score) values('21','3.30','2');
insert into Threehurdle_Score(age,num,score) values('21','3.20','1');
insert into Threehurdle_Score(age,num,score) values('22','3.40','3');
insert into Threehurdle_Score(age,num,score) values('22','3.30','2');
insert into Threehurdle_Score(age,num,score) values('22','3.20','1');
insert into Threehurdle_Score(age,num,score) values('23','3.40','3');
insert into Threehurdle_Score(age,num,score) values('23','3.30','2');
insert into Threehurdle_Score(age,num,score) values('23','3.20','1');
insert into Threehurdle_Score(age,num,score) values('24','3.40','3');
insert into Threehurdle_Score(age,num,score) values('24','3.30','2');
insert into Threehurdle_Score(age,num,score) values('24','3.20','1');

insert into Threehurdle_Score(age,num,score) values('25','3.50','3');
insert into Threehurdle_Score(age,num,score) values('25','3.40','2');
insert into Threehurdle_Score(age,num,score) values('25','3.30','1');
insert into Threehurdle_Score(age,num,score) values('26','3.50','3');
insert into Threehurdle_Score(age,num,score) values('26','3.40','2');
insert into Threehurdle_Score(age,num,score) values('26','3.30','1');
insert into Threehurdle_Score(age,num,score) values('27','3.50','3');
insert into Threehurdle_Score(age,num,score) values('27','3.40','2');
insert into Threehurdle_Score(age,num,score) values('27','3.30','1');
insert into Threehurdle_Score(age,num,score) values('28','3.50','3');
insert into Threehurdle_Score(age,num,score) values('28','3.40','2');
insert into Threehurdle_Score(age,num,score) values('28','3.30','1');
insert into Threehurdle_Score(age,num,score) values('29','3.50','3');
insert into Threehurdle_Score(age,num,score) values('29','3.40','2');
insert into Threehurdle_Score(age,num,score) values('29','3.30','1');

